steps:
  build:
    image: rust:nightly-bookworm
    commands:
      - apt-get update
      - apt-get install -y make xorriso nasm
      - rustup target add x86_64-unknown-none
      - rustup component add rustfmt rust-src
      - make

  test:
    image: rust:nightly-bookworm
    commands:
      - apt-get update
      - apt-get install -y make xorriso nasm qemu-system-x86
      - rustup target add x86_64-unknown-none
      - rustup component add rust-src
      - make test-iso
      - |
        set +e
        qemu-system-x86_64 \
          -cdrom oxenna_tests.iso \
          -m 256M \
          -serial stdio \
          -display none \
          -device isa-debug-exit,iobase=0xf4,iosize=0x04
        status=$?
        set -e

        if [ "$status" -eq 33 ]; then
          exit 0
        fi

        exit "$status"

  release:
    image: woodpeckerci/plugin-release
    depends_on:
      - build
      - test
    settings:
      files:
        - oxenna.iso
      api-key:
        from_secret: codeberg_token
      tag: ${CI_COMMIT_TAG}
    when:
      - event: tag
