#!/usr/bin/env python3
"""Small, dependency-aware Kconfig/menuconfig implementation for Oxenna.

It intentionally implements the subset needed by this project: bool symbols,
menus, defaults, and boolean `depends on` expressions. The generated
`.config` follows the familiar Linux-kconfig format and build/config.mk turns
selected symbols into Cargo features.
"""
from __future__ import annotations

import argparse
import curses
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KCONFIG = ROOT / "Kconfig"
DOTCONFIG = ROOT / ".config"
BUILD_DIR = ROOT / "out" / "config"
CONFIG_MK = BUILD_DIR / "config.mk"

@dataclass
class Symbol:
    name: str
    prompt: str = ""
    default: bool = False
    depends: list[list[str]] = field(default_factory=list)
    value: bool = False

@dataclass
class Menu:
    title: str
    symbols: list[Symbol] = field(default_factory=list)


def parse_kconfig(path: Path):
    menus: list[Menu] = []
    current: Menu | None = None
    symbol: Symbol | None = None
    mainmenu = "Oxenna Kernel Configuration"

    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("mainmenu"):
            m = re.search(r'"(.*)"', line)
            if m:
                mainmenu = m.group(1)
        elif line.startswith("menu "):
            m = re.search(r'"(.*)"', line)
            current = Menu(m.group(1) if m else line[5:].strip())
            menus.append(current)
        elif line == "endmenu":
            current = None
        elif line.startswith("config "):
            if current is None:
                raise ValueError("config outside menu: " + line)
            symbol = Symbol(line.split(None, 1)[1].strip())
            current.symbols.append(symbol)
        elif line == "bool" or line.startswith("bool "):
            if symbol is None:
                raise ValueError("bool without config")
            m = re.search(r'"(.*)"', line)
            symbol.prompt = m.group(1) if m else symbol.name
        elif line.startswith("default "):
            if symbol is None:
                raise ValueError("default without config")
            symbol.default = line.split()[1].lower() in ("y", "yes", "true", "1")
        elif line.startswith("depends on "):
            if symbol is None:
                raise ValueError("depends on without config")
            expr = line[len("depends on "):].strip()
            # Each `&&` term is a simple symbol for this project's Kconfig.
            symbol.depends.append([x.strip() for x in expr.split("&&") if x.strip()])
        elif line.startswith(("---", "help", "comment")):
            continue
        else:
            raise ValueError(f"unsupported Kconfig syntax: {line}")

    return mainmenu, menus


def all_symbols(menus):
    return {s.name: s for m in menus for s in m.symbols}


def dependency_ok(sym: Symbol, symbols: dict[str, Symbol]) -> bool:
    # Every `depends on` line is ANDed; terms on one line are also ANDed.
    return all(symbols.get(dep, Symbol(dep)).value for group in sym.depends for dep in group)


def normalize(symbols):
    changed = True
    while changed:
        changed = False
        for sym in symbols.values():
            if sym.value and not dependency_ok(sym, symbols):
                sym.value = False
                changed = True


def load_config(symbols):
    if DOTCONFIG.exists():
        for raw in DOTCONFIG.read_text().splitlines():
            m = re.match(r"CONFIG_([A-Za-z0-9_]+)=(y|n)$", raw.strip())
            if m and m.group(1) in symbols:
                symbols[m.group(1)].value = m.group(2) == "y"
    else:
        for sym in symbols.values():
            sym.value = sym.default
    normalize(symbols)


def save_config(symbols):
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "#",
        "# Automatically generated by make menuconfig; do not edit by hand.",
        "#",
    ]
    for name in sorted(symbols):
        if symbols[name].value:
            lines.append(f"CONFIG_{name}=y")
        else:
            lines.append(f"# CONFIG_{name} is not set")
    DOTCONFIG.write_text("\n".join(lines) + "\n")

    features = [s.name.lower() for s in symbols.values() if s.value]
    lines = [
        "# Generated by scripts/kconfig.py.  Source: .config",
    ]
    for sym in sorted(symbols.values(), key=lambda x: x.name):
        lines.append(f"CONFIG_{sym.name} := {'y' if sym.value else 'n'}")
    lines += [
        "CARGO_FEATURES := " + " ".join(features),
        "CARGO_FEATURE_ARGS := " + ("--features \"" + " ".join(features) + "\"" if features else ""),
    ]
    CONFIG_MK.write_text("\n".join(lines) + "\n")


def toggle(sym, symbols):
    if not sym.value:
        if dependency_ok(sym, symbols):
            sym.value = True
    else:
        sym.value = False
        # Kconfig-style dependency propagation: dependent features turn off.
        normalize(symbols)


def render(stdscr, mainmenu, menus, symbols):
    curses.curs_set(0)
    stdscr.keypad(True)
    idx = 0
    menu_idx = 0
    flat = [(m, s) for m in menus for s in m.symbols]
    dirty = False

    while True:
        stdscr.erase()
        h, w = stdscr.getmaxyx()
        title = f" {mainmenu} "
        stdscr.addnstr(0, max(0, (w-len(title))//2), title, w-1, curses.A_BOLD)
        stdscr.addnstr(1, 2, "Arrow keys: navigate   Space: toggle   S: save   Q: quit", w-4)
        stdscr.addnstr(2, 2, "Disabled entries have unmet dependencies.", w-4, curses.A_DIM)

        row = 4
        start = max(0, idx - max(0, h - 8))
        end = min(len(flat), start + max(1, h - 8))
        last_menu = None
        for i in range(start, end):
            menu, sym = flat[i]
            if menu is not last_menu:
                stdscr.addnstr(row, 3, f"{menu.title}", w-6, curses.A_BOLD)
                row += 1
                last_menu = menu
            enabled = dependency_ok(sym, symbols)
            marker = "*" if sym.value else " "
            if not enabled:
                marker = "-"
            text = f"  [{marker}] {sym.prompt}"
            attr = curses.A_REVERSE if i == idx else curses.A_NORMAL
            if not enabled:
                attr |= curses.A_DIM
            stdscr.addnstr(row, 5, text, w-8, attr)
            row += 1

        if flat:
            _, current = flat[idx]
            deps = [d for group in current.depends for d in group]
            status = "enabled" if current.value else "disabled"
            if not dependency_ok(current, symbols):
                status = "disabled (dependency)"
            footer = f" {current.name}: {status}"
            if deps:
                footer += "   depends on: " + ", ".join(deps)
            stdscr.addnstr(h-2, 2, footer, w-4, curses.A_DIM)
        stdscr.refresh()

        key = stdscr.getch()
        if key in (ord('q'), ord('Q'), 27):
            if dirty:
                # Save automatically, matching the convenient behavior users
                # expect from a build configuration command.
                save_config(symbols)
            return
        if key in (curses.KEY_DOWN, ord('j')):
            idx = (idx + 1) % len(flat)
        elif key in (curses.KEY_UP, ord('k')):
            idx = (idx - 1) % len(flat)
        elif key in (ord(' '), curses.KEY_ENTER, 10, 13):
            _, sym = flat[idx]
            before = sym.value
            toggle(sym, symbols)
            dirty |= before != sym.value
        elif key in (ord('s'), ord('S')):
            save_config(symbols)
            dirty = False
            stdscr.addnstr(h-1, 2, "Saved .config", w-4, curses.A_BOLD)
            stdscr.refresh()
            curses.napms(400)


def menuconfig():
    mainmenu, menus = parse_kconfig(KCONFIG)
    symbols = all_symbols(menus)
    load_config(symbols)
    curses.wrapper(render, mainmenu, menus, symbols)
    save_config(symbols)
    print(f"Configuration written to {DOTCONFIG}")
    print(f"Cargo features: {', '.join(s.name.lower() for s in symbols.values() if s.value) or '(none)'}")


def olddefconfig():
    _, menus = parse_kconfig(KCONFIG)
    symbols = all_symbols(menus)
    load_config(symbols)
    save_config(symbols)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("command", choices=("menuconfig", "olddefconfig", "sync"))
    args = ap.parse_args()
    if args.command == "menuconfig":
        if not sys.stdin.isatty() or not sys.stdout.isatty():
            print("make menuconfig requires an interactive terminal", file=sys.stderr)
            return 2
        menuconfig()
    else:
        olddefconfig()
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
